"""empty message

Revision ID: 172eae95b701
Revises: ad6bc39d0a33
Create Date: 2023-09-28 13:56:23.466758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172eae95b701'
down_revision = 'ad6bc39d0a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.alter_column('favourite_JSON',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.String(length=6500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.alter_column('favourite_JSON',
               existing_type=sa.String(length=6500),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=False)

    # ### end Alembic commands ###
