"""empty message

Revision ID: 776315c0de37
Revises: fe2a16a185cf
Create Date: 2023-09-19 17:23:24.714815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776315c0de37'
down_revision = 'fe2a16a185cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_username_key', ['username'])

    # ### end Alembic commands ###
