"""empty message

Revision ID: ad6bc39d0a33
Revises: e7819aaf287a
Create Date: 2023-09-28 09:21:46.521089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6bc39d0a33'
down_revision = 'e7819aaf287a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_JSON', sa.String(length=3000), nullable=False))
        batch_op.drop_column('recipe_label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_label', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
        batch_op.drop_column('favourite_JSON')

    # ### end Alembic commands ###
