"""empty message

Revision ID: ae4b14851f2c
Revises: 172eae95b701
Create Date: 2023-09-28 14:00:12.751798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4b14851f2c'
down_revision = '172eae95b701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.alter_column('favourite_JSON',
               existing_type=sa.VARCHAR(length=6500),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.alter_column('favourite_JSON',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=6500),
               existing_nullable=False)

    # ### end Alembic commands ###
